name: Pipeline CI-CD

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Clonar repositorio
    uses: actions/checkout@v4

  - name: Configurar Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Dar permisos Maven
    run: chmod +x mvnw

  - name: Ejecutar tests
    run: ./mvnw clean test

  - name: Generar reporte JaCoCo
    run: ./mvnw jacoco:report

  - name: Build proyecto
    run: ./mvnw clean package -DskipTests

  - name: Ejecutar análisis Snyk
    uses: snyk/actions/maven@master
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  - name: Generar reporte JSON Snyk
    if: always()
    run: |
      snyk test --json > snyk-report.json || echo "Snyk encontró vulnerabilidades"

  - name: Subir reporte Snyk
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: snyk-report
      path: snyk-report.json

  - name: Build Docker
    run: docker build -t ms-gestionusuarios .

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: app
      path: target/*.jar